name: KVaaS

on:
  schedule:
    - cron:  '* * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Ping
        run: |
          curl https://api.keyvalue.xyz/ping

      - name: Create new key-value and set value
        run: |
          KV=$(curl -X POST -s https://api.keyvalue.xyz/new/tester)
          echo $KV
          curl -X POST --data "my-value" $KV
          curl $KV
